apiVersion: v1
kind: ReplicationController
metadata:
  name: presto-worker
spec:
  replicas: 4 #16
  template:
    metadata:
      labels:
        app: presto
    spec:
      containers:
        - name: presto-worker
          image: thiagodiogo/docker-presto:0.214
          imagePullPolicy: Always
          env:
            - name: CONFIG_CONF_COORDINATOR
              value: "false"
            - name: CONFIG_CONF_QUERY_MAX___MEMORY___PER___NODE
              value: 25GB
            - name: CONFIG_CONF_QUERY_MAX___TOTAL___MEMORY___PER___NODE
              value: 25GB
            - name: CONFIG_CONF_MEMORY_HEAP___HEADROOM___PER___NODE
              value: 4GB
            - name: CONFIG_CONF_RESOURCES_RESERVED___SYSTEM___MEMORY
              value: 4GB
            - name: CONFIG_CONF_DISCOVERY_URI
              value: http://presto-coordinator.presto:8080
            - name: JVM_CONF_XMS
              value: "28G"
            - name: JVM_CONF_XMX
              value: "30G"
            - name: HIVE_CONF_HIVE_METASTORE_URI
              value: thrift://hive-metastore.presto:9083
            - name: LOG_CONF_COM_FACEBOOK_PRESTO
              value: INFO
          resources:
            requests:
              memory: "28Gi"
            limits:
              memory: "30Gi"
          ports:
            - containerPort: 8889


#SQL Error [65544]: Query failed (#20181128_222824_00000_bnenr): Could not communicate with the remote task.
#The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (172.31.31.244:8080)

# root@presto-x2lbq:~# printenv | grep CONFIG_CONF
# CONFIG_CONF_QUERY_MAX___MEMORY___PER___NODE=128MB
# CONFIG_CONF_QUERY_MAX___MEMORY=128MB
#
# Configuring /opt/presto/etc/config.properties
#  - Setting query.max-memory-per-node=128MB
#  - Setting query.max-memory=128MB
# Configuring /opt/presto/etc/log.properties
# Configuring /opt/presto/etc/node.properties
# Configuring /opt/presto/etc/catalog/hive.properties
#  - Setting hive.metastore.uri=thrift://hive-metastore.presto:9083
#
#  root@presto-x2lbq:~# cat /opt/presto/etc/config.properties
# coordinator=true
# node-scheduler.include-coordinator=true
# http-server.http.port=8080
# query.max-memory=128MB
# query.max-memory-per-node=128MB
# discovery-server.enabled=true
# discovery.uri=http://localhost:8080
